
name: 'job_portfolio'
version: '1.0.0'
config-version: 2

model-paths: ["models"]  

test-paths: ["test"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"

models:
  job_portfolio:
  
    staging:  
      +materialized: view
      +on_schema_change: sync_all_columns
      +tags: ['staging']
      +persist_docs:
          relation: true
          columns: true
          
    intermediate_mart: 
      +materialized: table
      +on_schema_change: sync_all_columns
      +tags: ['intermediate']
      +persist_docs:
          relation: true
          columns: true
          
    mart:  
      +materialized: table
      +on_schema_change: sync_all_columns
      +tags: ['mart']
      +persist_docs:
          relation: true
          columns: true

snapshots:
  +materialized: snapshot
  +on_schema_change: sync_all_columns
  +strategy: 'timestamp'
  +unique_key: 'EXTRACTED_AT'

    
