WITH cleaned_and_renamed AS 
(
SELECT

  ABS(COALESCE(TRY_CAST(TRIM("INDEX") AS INT), 0)) AS  JOB_ID,
  COALESCE(TRIM("JOB TITLE"),'NA') AS JOB_TITLE,
  COALESCE(TRIM("SALARY ESTIMATE"), 'NA') AS SALARY_ESTIMATE,
  ABS(COALESCE(TRY_CAST(TRIM(RATING) AS NUMERIC(4,2)), 0)) AS JOB_RATING,
  COALESCE(TRIM("JOB DESCRIPTION"), 'NA') AS JOB_DESCRIPTION,
  COALESCE(TRIM("COMPANY NAME"), 'NA') AS COMPANY_NAME,
  COALESCE(TRIM(LOCATION), 'NA') AS COMPANY_LOCATION,
  COALESCE(TRIM(HEADQUARTERS), 'NA') AS COMPANY_HEADQUARTERS,
  COALESCE(TRIM(SIZE),'NA') AS COMPANY_SIZE,
  ABS(COALESCE(TRY_CAST(TRIM(FOUNDED) AS INT), 0)) AS COMPANY_FOUNDED,
  COALESCE(TRIM("TYPE OF OWNERSHIP"), 'NA') AS OWNERSHIP_TYPE,
  COALESCE(TRIM(INDUSTRY), 'NA') AS INDUSTRY,
  COALESCE(TRIM(SECTOR), 'NA') AS SECTOR,
  COALESCE(TRIM(REVENUE), 'NA') AS APPROX_REVENUE,
  COALESCE(TRIM(COMPETITORS), 'NA') AS COMPETITORS

FROM {{ source('source_job_portfolio', 'UNCLEANED_DS_JOBS') }}
)
select * from cleaned_and_renamed





  
